# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test CMC

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: python:3.7
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Mark repo safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Checkout submodules
      run: git submodule update --init --recursive 
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc gfortran openmpi-bin libopenmpi-dev cmake libhdf5-serial-dev libgsl-dev libcfitsio-dev
    - name: Build CMC
      run: |
        mkdir build
        cd build
        FC=mpifort CC=mpicc cmake .. -DCMAKE_INSTALL_PREFIX=../ci
        make install
    - name: Test with pytest
      run: |
        cd ci
        bash run_cmc_tests.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
